#ifndef STRING_CHARMAP_H
#define STRING_CHARMAP_H

//#pragma charmap ('0',  0)
#pragma charmap ('1',  1)
#pragma charmap ('2',  2)
#pragma charmap ('3',  3)
#pragma charmap ('4',  4)
#pragma charmap ('5',  5)
#pragma charmap ('6',  6)
#pragma charmap ('7',  7)
#pragma charmap ('8',  8)
#pragma charmap ('9',  9)
#pragma charmap ('A', 10)
#pragma charmap ('B', 11)
#pragma charmap ('C', 12)
#pragma charmap ('D', 13)
#pragma charmap ('E', 14)
#pragma charmap ('F', 15)
#pragma charmap ('G', 16)
#pragma charmap ('H', 17)
#pragma charmap ('I', 18)
#pragma charmap ('J', 19)
#pragma charmap ('K', 20)
#pragma charmap ('L', 21)
#pragma charmap ('M', 22)
#pragma charmap ('N', 23)
#pragma charmap ('O', 24)
#pragma charmap ('P', 25)
#pragma charmap ('Q', 26)
#pragma charmap ('R', 27)
#pragma charmap ('S', 28)
#pragma charmap ('T', 29)
#pragma charmap ('U', 30)
#pragma charmap ('V', 31)
#pragma charmap ('W', 32)
#pragma charmap ('X', 33)
#pragma charmap ('Y', 34)
#pragma charmap ('Z', 35)
#pragma charmap ('a', 36)
#pragma charmap ('b', 37)
#pragma charmap ('c', 38)
#pragma charmap ('d', 39)
#pragma charmap ('e', 40)
#pragma charmap ('f', 41)
#pragma charmap ('g', 42)
#pragma charmap ('h', 43)
#pragma charmap ('i', 44)
#pragma charmap ('j', 45)
#pragma charmap ('k', 46)
#pragma charmap ('l', 47)
#pragma charmap ('m', 48)
#pragma charmap ('n', 49)
#pragma charmap ('o', 50)
#pragma charmap ('p', 51)
#pragma charmap ('q', 52)
#pragma charmap ('r', 53)
#pragma charmap ('s', 54)
#pragma charmap ('t', 55)
#pragma charmap ('u', 56)
#pragma charmap ('v', 57)
#pragma charmap ('w', 58)
#pragma charmap ('x', 59)
#pragma charmap ('y', 60)
#pragma charmap ('z', 61)
#pragma charmap ('.', 62)
#pragma charmap (':', 63)
#pragma charmap ('!', 0x88)
#pragma charmap ('?', 0x89)
#pragma charmap (' ', 0x58)

#define CHECKBOX_OFF 0x74
#define CHECKBOX_ON 0x75

#endif

